### ISSUE TITLE
The "path" argument must be of type string. Received type object (Node v10.16.0)

### ISSUE THREAD

**Issue by ComLock** [pfraces/udm#4]
```bash
$ git-install
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at Object.<anonymous> (/Users/SNIP/.nvm/versions/node/v10.16.0/lib/node_modules/git-install/src/git-install.js:19:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by ComLock** [comment]
Looks like shelljs.pwd() returns an object rather than a string.
Setting "shelljs": "0.6.1" in package.json is a quickfix.

**Comment by ComLock** [comment]
I'm on mac btw. Darwin Kernel Version 17.7.0

**Comment by ComLock** [comment]
The correct solution is to add .toString() like this:

```
var DEST_DIR = path.resolve(sh.pwd().toString(), 'git-dependencies');
```

And set "shelljs": "^0.8.3" in package.json


Reason:
https://github.com/shelljs/shelljs#shellstringstr

**Comment by ComLock** [comment]
Looks like other people has seen this problem before:
https://github.com/Delfil/git-install/commit/9d3d4877a96b2e1455f6d81f7907e07913d0a7f1

**Comment by pfraces** [comment]
PR merged

**Comment by pfraces** [comment]
Also deps has been updated with caret ranges
